import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { spawnSync } from "node:child_process";

const cli = path.resolve("src/cli.js");

test("read batch and dependency-aware verification are public CLI contracts", () => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), "agentshell-advanced-cli-"));
  const initialized = spawnSync("git", ["init", "-q"], { cwd: root, encoding: "utf8" });
  assert.equal(initialized.status, 0, initialized.stderr);
  fs.writeFileSync(path.join(root, "package.json"), JSON.stringify({
    name: "fixture",
    scripts: { test: "node --test" }
  }));
  fs.writeFileSync(path.join(root, "source.js"), "one\ntwo\nthree\n");

  const read = invoke(root, [
    "read", "batch", "--target", "source.js:1:2", "--target", "missing.js@head=2", "--compact"
  ]);
  assert.equal(read.status, 0, read.stderr);
  const batch = JSON.parse(read.stdout);
  assert.equal(batch.protocolVersion, "agentshell.read-batch.v1");
  assert.equal(batch.status, "partial");
  assert.deepEqual(batch.results.map((entry) => entry.ok), [true, false]);

  const verify = invoke(root, ["verify", "changed", "--include-dependents", "--compact"]);
  assert.equal(verify.status, 0, verify.stderr);
  const plan = JSON.parse(verify.stdout);
  assert.equal(plan.protocolVersion, "agentshell.verify-changed.v1");
  assert.equal(plan.includeDependents, true);
});

test("workspace audit and Go locator are public CLI contracts", () => {
  const parent = fs.mkdtempSync(path.join(os.tmpdir(), "agentshell-audit-cli-"));
  const first = makeGitRoot(parent, "first");
  const second = makeGitRoot(parent, "second");
  fs.writeFileSync(path.join(first, "go.mod"), "module example.test/first\n\ngo 1.22\n");
  fs.writeFileSync(path.join(first, "generated.pb.go"), "// Code generated by protoc-gen-go. DO NOT EDIT.\npackage first\n");

  const audited = invoke(first, ["workspace", "audit", "--root", first, "--root", second, "--compact"]);
  assert.equal(audited.status, 0, audited.stderr);
  const audit = JSON.parse(audited.stdout);
  assert.equal(audit.protocolVersion, "agentshell.workspace-audit.v1");
  assert.equal(audit.summary.repositoryCount, 2);
  assert.doesNotMatch(audited.stdout, new RegExp(escapeRegExp(parent)));

  const located = invoke(first, ["go", "locate", "generated", "--kind", "pb", "--compact"]);
  assert.equal(located.status, 0, located.stderr);
  const go = JSON.parse(located.stdout);
  assert.equal(go.protocolVersion, "agentshell.go-locate.v1");
  assert.equal(go.results[0].file, "generated.pb.go");
});

test("background job lifecycle is available through the public CLI", async () => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), "agentshell-job-cli-"));
  fs.writeFileSync(path.join(root, "package.json"), JSON.stringify({ name: "fixture" }));
  const started = invoke(root, ["job", "start", "--timeout-ms", "5000", "--", process.execPath, "-e", "console.log('ready')"]);
  assert.equal(started.status, 0, started.stderr);
  const start = JSON.parse(started.stdout);
  assert.equal(start.protocolVersion, "agentshell.job.v1");
  const jobId = start.job.jobId;

  let status;
  for (let attempt = 0; attempt < 80; attempt += 1) {
    await new Promise((resolve) => setTimeout(resolve, 25));
    const checked = invoke(root, ["job", "status", jobId, "--compact"]);
    assert.equal(checked.status, 0, checked.stderr);
    status = JSON.parse(checked.stdout);
    if (!["starting", "running"].includes(status.job.status)) break;
  }
  assert.equal(status.job.status, "completed");

  const delta = invoke(root, ["job", "delta", jobId, "--compact"]);
  assert.equal(delta.status, 0, delta.stderr);
  assert.match(JSON.parse(delta.stdout).output.stdout, /ready/);
});

test("read failures use a non-zero exit code and job telemetry omits argv secrets", () => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), "agentshell-cli-safety-"));
  fs.writeFileSync(path.join(root, "package.json"), JSON.stringify({ name: "fixture" }));
  const missing = invoke(root, ["read", "missing.txt", "--head", "2"]);
  assert.equal(missing.status, 1, missing.stderr);
  assert.equal(JSON.parse(missing.stdout).ok, false);

  const secret = "ultra-secret-telemetry-value";
  const started = invoke(root, ["job", "start", "--", process.execPath, "-e", "process.exit(0)", "--password", secret]);
  assert.equal(started.status, 0, started.stderr);
  const events = fs.readFileSync(path.join(root, ".agentshell", "events.jsonl"), "utf8");
  assert.doesNotMatch(events, new RegExp(secret));
  assert.match(events, /<argv-redacted>/);
});

function makeGitRoot(parent, name) {
  const root = path.join(parent, name);
  fs.mkdirSync(root);
  const result = spawnSync("git", ["init", "-q"], { cwd: root, encoding: "utf8" });
  assert.equal(result.status, 0, result.stderr);
  return root;
}

function invoke(root, args) {
  return spawnSync(process.execPath, [cli, ...args], { cwd: root, encoding: "utf8", timeout: 30_000 });
}

function escapeRegExp(value) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}
