import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";

import { goLocateCommand, parseGoLocateArgs } from "../src/commands/go-locate.js";
import {
  classifyGeneratedGoFile,
  parseGoListJson,
  runGoLocator
} from "../src/core/go-locator.js";

test("command parser exposes three concrete modes and rejects ambiguous or injected queries", () => {
  assert.deepEqual(parseGoLocateArgs(["symbol", "Client", "--package", "example.test/sdk", "--max-results", "4"]).value, {
    mode: "symbol", compact: true, query: "Client", package: "example.test/sdk", maxResults: 4
  });
  assert.equal(parseGoLocateArgs(["dependency", "example.org/lib"]).ok, true);
  assert.equal(parseGoLocateArgs(["generated", "--kind", "grpc"]).ok, true);
  assert.equal(parseGoLocateArgs(["symbol"]).error.code, "INVALID_ARGUMENT");
  assert.equal(parseGoLocateArgs(["dependency", "--help"]).error.code, "INVALID_ARGUMENT");
  assert.equal(parseGoLocateArgs(["generated", "--root", "/"]).error.code, "INVALID_ARGUMENT");
});

test("go list stream parser handles concatenated objects and rejects malformed metadata", () => {
  const parsed = parseGoListJson('{"ImportPath":"b","Dir":"/b"}\n{"ImportPath":"a","Dir":"/a","Note":"} in string"}\n');
  assert.equal(parsed.ok, true);
  assert.deepEqual(parsed.packages.map((pkg) => pkg.ImportPath), ["a", "b"]);
  assert.equal(parseGoListJson('{"ImportPath":').error.code, "GO_LOCATE_METADATA_INVALID");
});

test("generated classifier recognizes protobuf, grpc, mocks, wire, and generic headers", () => {
  assert.equal(classifyGeneratedGoFile("thing.pb.go").kind, "pb");
  assert.equal(classifyGeneratedGoFile("thing_grpc.pb.go").kind, "grpc");
  assert.equal(classifyGeneratedGoFile("mock_client.go").kind, "mock");
  assert.equal(classifyGeneratedGoFile("wire_gen.go").kind, "wire");
  assert.equal(classifyGeneratedGoFile("zz.go", "// Code generated by custom; DO NOT EDIT.").kind, "generic");
  assert.equal(classifyGeneratedGoFile("normal.go", "package sample").generated, false);
});

test("symbol lookup uses listed package files, returns stable redacted paths, and disables network", async () => {
  const fixture = goFixture();
  const calls = [];
  const result = await runGoLocator(fixture.root, { mode: "symbol", query: "Client", maxResults: 10 }, {
    env: { ...process.env, GOFLAGS: "-toolexec=unexpected", GOTOOLCHAIN: "auto", GOWORK: "/tmp/outside.work" },
    runProcess: fakeRunner(fixture, calls)
  });

  assert.equal(result.ok, true);
  assert.deepEqual(result.results.map((entry) => [entry.package, entry.file, entry.line]), [
    ["example.test/app", "client.go", 3],
    ["example.org/sdk/client", "module:example.org/sdk@v1.2.3/client.go", 3]
  ]);
  assert.deepEqual(result.results.map((entry) => entry.source), ["workspace", "module-cache"]);
  assert.equal(JSON.stringify(result).includes(os.homedir()), false);
  assert.equal(result.privacy.dependencyCachePathsExposed, false);
  assert.deepEqual(calls.map((call) => call.argv), [
    ["go", "env", "GOMODCACHE"],
    ["go", "list", "-deps", "-json", "./..."]
  ]);
  assert.ok(calls.every((call) => call.options.env.GOPROXY === "off" && call.options.env.GOSUMDB === "off"));
  assert.ok(calls.every((call) => call.options.env.GOFLAGS === "-mod=readonly"));
  assert.ok(calls.every((call) => call.options.env.GOTOOLCHAIN === "local" && call.options.env.GOENV === "off"));
  assert.ok(calls.every((call) => call.options.env.GOWORK === undefined));
});

test("dependency lookup matches one concrete module and never exposes cache directories", async () => {
  const fixture = goFixture();
  const result = await goLocateCommand(fixture.root, ["dependency", "example.org/sdk", "--compact"], {
    runProcess: fakeRunner(fixture, [])
  });

  assert.equal(result.ok, true);
  assert.equal(result.mode, "dependency");
  assert.deepEqual(result.results, [{
    kind: "dependency",
    package: "example.org/sdk/client",
    module: "example.org/sdk@v1.2.3",
    source: "module-cache",
    standardLibrary: false,
    workspace: false
  }]);
  assert.equal(JSON.stringify(result).includes(fixture.cache), false);
  assert.equal(JSON.stringify(result).includes(fixture.externalModule), false);
});

test("generated lookup only reads go-list workspace files and supports kind filters", async () => {
  const fixture = goFixture();
  const all = await runGoLocator(fixture.root, { mode: "generated" }, { runProcess: fakeRunner(fixture, []) });
  assert.equal(all.ok, true);
  assert.deepEqual(all.results.map((entry) => [entry.generator, entry.file]), [
    ["mock", "mock_client.go"],
    ["grpc", "service_grpc.pb.go"],
    ["wire", "wire_gen.go"]
  ]);
  const grpc = await runGoLocator(fixture.root, { mode: "generated", kind: "grpc" }, { runProcess: fakeRunner(fixture, []) });
  assert.deepEqual(grpc.results.map((entry) => entry.file), ["service_grpc.pb.go"]);
});

test("core rejects shell patterns, path traversal, broad dependency searches, and invalid limits", async () => {
  const fixture = goFixture();
  const runner = fakeRunner(fixture, []);
  assert.equal((await runGoLocator(fixture.root, { mode: "symbol", query: "Client;touch" }, { runProcess: runner })).error.code, "GO_LOCATE_QUERY_INVALID");
  assert.equal((await runGoLocator(fixture.root, { mode: "dependency", query: "../..." }, { runProcess: runner })).error.code, "GO_LOCATE_QUERY_INVALID");
  assert.equal((await runGoLocator(fixture.root, { mode: "dependency", query: "example.org/*" }, { runProcess: runner })).error.code, "GO_LOCATE_QUERY_INVALID");
  assert.equal((await runGoLocator(fixture.root, { mode: "generated", maxResults: 1000 }, { runProcess: runner })).error.code, "GO_LOCATE_LIMIT_INVALID");
});

test("timeout is structured and prevents unbounded metadata work", async () => {
  const fixture = goFixture();
  const result = await runGoLocator(fixture.root, { mode: "symbol", query: "Client", timeoutMs: 20 }, {
    runProcess: async (argv) => argv[1] === "env"
      ? execution(fixture.cache)
      : { ...execution(""), exitCode: 124, timedOut: true }
  });
  assert.equal(result.ok, false);
  assert.equal(result.error.code, "GO_LOCATE_TIMEOUT");
  assert.equal(result.error.details.timedOut, true);
});

test("schema describes the protocol and all three modes", () => {
  const schema = JSON.parse(fs.readFileSync(new URL("../schemas/go-locate.schema.json", import.meta.url), "utf8"));
  assert.equal(schema.oneOf[0].properties.protocolVersion.const, "agentshell.go-locate.v1");
  assert.deepEqual(schema.oneOf[0].properties.mode.enum, ["symbol", "dependency", "generated"]);
  assert.equal(schema.oneOf[0].properties.results.maxItems, 200);
});

function goFixture() {
  const base = fs.mkdtempSync(path.join(os.tmpdir(), "agentshell-go-locate-"));
  const root = path.join(base, "workspace");
  const cache = path.join(base, "private-home", "go", "pkg", "mod");
  const externalModule = path.join(cache, "example.org", "sdk@v1.2.3");
  fs.mkdirSync(root, { recursive: true });
  fs.mkdirSync(externalModule, { recursive: true });
  fs.writeFileSync(path.join(root, "go.mod"), "module example.test/app\n\ngo 1.22\n");
  fs.writeFileSync(path.join(root, "client.go"), "package app\n\n type Client struct{}\n");
  fs.writeFileSync(path.join(root, "mock_client.go"), "// Code generated by MockGen. DO NOT EDIT.\npackage app\n");
  fs.writeFileSync(path.join(root, "service_grpc.pb.go"), "// Code generated by protoc-gen-go-grpc. DO NOT EDIT.\npackage app\n");
  fs.writeFileSync(path.join(root, "wire_gen.go"), "// Code generated by Wire. DO NOT EDIT.\npackage app\n");
  fs.writeFileSync(path.join(externalModule, "client.go"), "package client\n\nfunc Client() {}\n");
  return { root, cache, externalModule };
}

function fakeRunner(fixture, calls) {
  return async (argv, cwd, options) => {
    calls.push({ argv, cwd, options });
    if (argv[1] === "env") return execution(`${fixture.cache}\n`);
    const local = {
      ImportPath: "example.test/app",
      Dir: fixture.root,
      GoFiles: ["wire_gen.go", "client.go", "service_grpc.pb.go", "mock_client.go"],
      Module: { Path: "example.test/app", Dir: fixture.root, Main: true }
    };
    const dependency = {
      ImportPath: "example.org/sdk/client",
      Dir: fixture.externalModule,
      GoFiles: ["client.go"],
      Module: { Path: "example.org/sdk", Version: "v1.2.3", Dir: fixture.externalModule }
    };
    const values = argv.includes("-deps") ? [dependency, local] : [local];
    return execution(values.map((value) => JSON.stringify(value)).join("\n"));
  };
}

function execution(stdout) {
  return {
    exitCode: 0,
    signal: null,
    durationMs: 1,
    timedOut: false,
    truncated: false,
    stdout,
    stderr: "",
    capturedBytes: Buffer.byteLength(stdout),
    observedBytes: Buffer.byteLength(stdout),
    outputLimitBytes: 4 * 1024 * 1024,
    spawnError: null
  };
}
